### ISSUE TITLE
You need to sign in or sign up before continuing when trying to sign in

### ISSUE THREAD

**Issue by GMolini** [waiting-for-dev/devise-jwt#98] opened 2018-07-10 12:17 UTC
Hi I keep getting an error when trying to sign in. Im using Rails::API, and Ive followed your wiki https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs

This is my sessions controller

`# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  def create
    super { |resource| @resource = resource }
  end

end
`

this is my routes.rb
` devise_for :users,
              defaults: { format: :json },
              controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'}`

DEvise::JWT.config

` #<#<Class:0x00000003a53a68>:0x00000003a52fa0 @config={:secret=>"SECRET", :expiration_time=>604800, :dispatch_requests=>nil, :revocation_requests=>nil, :aud_header=>nil, :request_formats=>{}}>`

Warden::JWTAuth.config

`#<#<Class:0x000000038a8c18>:0x00000002ae7ef8 @config={:secret=>"SECRET", :expiration_time=>604800, :aud_header=>"JWT_AUD", :mappings=>{:user=>"User"}, :dispatch_requests=>[["POST", /^\/users\/sign_in$/], ["POST", /^\/users$/]], :revocation_requests=>[["DELETE", /^\/users\/sign_out$/]], :revocation_strategies=>{:user=>"JWTBlacklist"}}>`
User generation works fine, but I havent been able to sign in yet. Any ideas why this can be happening?

Devise mappings

`{:user=>#<Devise::Mapping:0x00000004685b10 @scoped_path="users", @singular=:user, @class_name="User", @klass=#<Devise::Getter:0x00000004685778 @name="User">, @path="users", @path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:sessions=>"users/sessions", :registrations=>"users/registrations", :passwords=>"devise/passwords"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :trackable, :jwt_authenticatable], @routes=[:session, :password, :registration], @used_routes=[:session, :password, :registration], @used_helpers=[:session, :password, :registration]>} `

Any idea why i cant sign in?

**Comment by waiting-for-dev** [comment] 2018-07-10 14:07
Hi @GMolini ,

please, could you paste the sign in request you are trying to perform (URL & request headers)?

**Comment by GMolini** [comment] 2018-07-10 14:20
Sure 

curl -X POST \
  http://localhost:3000/users/sign_in \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
  "email" : "a@gmail.com",
  "password" : "aaaaaa"
}'

**Comment by waiting-for-dev** [comment] 2018-07-11 08:43
Your configuration seems ok. Which response do you get from that request (body and response headers)? Also, do you have `respond_to :json` in your `ApplicationController`?

**Comment by GMolini** [comment] 2018-07-11 09:09
Should I respnd you here or in github? And yeah, I have respond_to :json in
my application controller

Response:
Headers:
Cache-Control →no-cache
Content-Type →application/json; charset=utf-8
Transfer-Encoding →chunked
Vary →Origin
X-Request-Id →e2fe1c43-b19b-4e29-a162-f371db2c06c0
X-Runtime →0.607982

Body:
{"error":"You need to sign in or sign up before continuing."}

**Comment by GMolini** [comment] 2018-07-11 12:56
Hi again,

So Ive been investigating a little. If I change my sessionscontroller to
this:

# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController

  def create

    user = User.find_by(email: login_params[:email])
    if user && user.valid_password?(login_params[:password])
      @current_user = user
      render json: { user: user.attributes.except('password',
'password_confirmation'), status: 200},
             status: 200
    else
      render json: {message: "Error, Unauthorized", status: 401},
             status: :unauthorized
    end
  end

  private
  def login_params
    params.permit(:email, :password)
  end
end

​

Login works, but no token is returned in the header.

**Comment by waiting-for-dev** [comment] 2018-07-11 13:53
> Should I respnd you here or in github? And yeah, I have respond_to :json in
my application controller

I answered in Github, but you probably got it in your email inbox. If you reply to the email, it is also published in Github.

> So Ive been investigating a little. If I change my sessionscontroller to
this:

With that controller, you are basically overriding devise behavior (you are not calling `warden.authenticate!`, for example), so `devise-jwt` is not doing anything.

In fact, `devise-jwt` is not responsible of the sign in process. So your problem is related with `devise` itself, as the `:database_authenticatable` strategy belongs to `devise`. I recommend you to try to disable `devise-jwt` to understand that the problem is not related with it, and then try to isolate your problem in a minimal application repository so that myself or someone else over stackoverflow can check it.

**Comment by GMolini** [comment] 2018-07-11 14:36
Oh god, found it! It was actually my fault.

The json I was using was incorrect. It should be

{ "user" :{
  "email" : "as@gmail.com",
  "password" : "aaaaaa"}}

instead of

{ "email" : "as@gmail.com",
  "password" : "aaaaaa"}

​

**Comment by waiting-for-dev** [comment] 2018-07-11 16:02
Good! Closing it, then.

**Closed by waiting-for-dev** 2018-07-11 16:02 UTC

**Comment by christophweegen** [comment] 2018-07-13 17:44
Hey @GMolini 

if you want to make 

> { "email" : "as@gmail.com",
  "password" : "aaaaaa"}

work too, without specifying the `user` root element in your json like 

> { "user" :{
  "email" : "as@gmail.com",
  "password" : "aaaaaa"}}

Rails already provides a mechanism for that by wrapping the json in your controller: 
http://api.rubyonrails.org/v5.2.0/classes/ActionController/ParamsWrapper.html

This helps to reduce uneccessary clutter in your json requests by shortening them :-)

**Comment by SOUMONSoum** [comment] 2019-05-18 04:06
Thanks @christophweegen
