### ISSUE TITLE
Erro on sign_out with JWT::DecodeError (No verification key available) In Production Environment

### ISSUE THREAD

**Issue by Leandro-b-03** [waiting-for-dev/devise-jwt#270] opened 2024-07-07 23:51 UTC
Hello everyone, I'm facing an issue that I can't find a solution anywhere.

I'm using the gem with Rails 7.1 API mode for customers, and works like a charm in development every went just fine til I deployed it on the production site, the sign_in, and sign_up work great, but when I try to sign_out it becomes a nightmare.

**To Reproduce**
My configuration on devise.rb:

``` ruby
  config.jwt do |jwt|
    jwt.secret = Rails.application.credentials.devise_jwt_secret_key!

    jwt.dispatch_requests = [
      ['POST', %r{^/api/v1/users/sign_in$}],
      ['POST', %r{^/api/v1/website/customers$}],
      ['POST', %r{^/api/v1/website/customers/sign_in$}],
      ['POST', %r{^/api/v1/website/customers/google_oauth2$}],
      ['POST', %r{^/api/v1/website/customers/google_oauth2/callback$}],
      ['GET',  %r{^/api/v1/website/customers/google_oauth2$}],
      ['GET',  %r{^/api/v1/website/customers/google_oauth2/callback$}]
    ]
    jwt.revocation_requests = [
      ['DELETE', %r{^/api/v1/users/sign_out$}],
      ['DELETE', %r{^/api/v1/website/customers/sign_out$}]
    ]
    jwt.expiration_time = 15.days.to_i
    jwt.request_formats = { user: [:json], customer: [:json] }
  end
```

The error:
```
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] JWT::DecodeError (No verification key available):
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5]   
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] jwt (2.8.2) lib/jwt/decode.rb:48:in `verify_signature'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] jwt (2.8.2) lib/jwt/decode.rb:32:in `decode_segments'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] jwt (2.8.2) lib/jwt.rb:31:in `block in decode'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] jwt (2.8.2) lib/jwt/deprecations.rb:8:in `context'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] jwt (2.8.2) lib/jwt.rb:30:in `decode'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/token_decoder.rb:27:in `decode'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/token_decoder.rb:21:in `rescue in call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/token_decoder.rb:18:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/token_revoker.rb:13:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:34:in `revoke_token'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:22:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack (3.1.6) lib/rack/builder.rb:277:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden-jwt_auth (0.9.0) lib/warden/jwt_auth/middleware.rb:22:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/cookies.rb:689:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] warden (1.2.9) lib/warden/manager.rb:34:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack (3.1.6) lib/rack/etag.rb:29:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack (3.1.6) lib/rack/conditional_get.rb:43:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack (3.1.6) lib/rack/head.rb:15:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] activesupport (7.1.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] railties (7.1.3.4) lib/rails/rack/logger.rb:37:in `call_app'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `block in call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `block in tagged'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:39:in `tagged'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] activesupport (7.1.3.4) lib/active_support/tagged_logging.rb:135:in `tagged'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] activesupport (7.1.3.4) lib/active_support/broadcast_logger.rb:240:in `method_missing'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] railties (7.1.3.4) lib/rails/rack/logger.rb:24:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/request_id.rb:28:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack (3.1.6) lib/rack/runtime.rb:24:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] activesupport (7.1.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/static.rb:25:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack (3.1.6) lib/rack/sendfile.rb:114:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] actionpack (7.1.3.4) lib/action_dispatch/middleware/ssl.rb:79:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] rack-cors (2.0.2) lib/rack/cors.rb:102:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] railties (7.1.3.4) lib/rails/engine.rb:536:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
23:32:08 web.1     | [9ccb41e3-ca85-4872-be1c-0485f506ece5] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

Somehow the secret is lost on the way and I'm not an expert in debugging gems, and I'm hoping for clarity if you guys can help me!

**Comment by waiting-for-dev** [comment] 2024-07-10 14:45
It looks you haven't setup `jwt.secret` in production. Please, see the Readme and https://stackoverflow.com/questions/64923974/no-verification-key-available-when-attempting-to-access-api-secured-by-devise can also help you.

**Comment by Leandro-b-03** [comment] 2024-07-10 17:10
Hello @waiting-for-dev thank you for the reply,

I have set it on rails credentials:
![image](https://github.com/waiting-for-dev/devise-jwt/assets/2287942/d1c86737-604e-467c-a2b1-bcf54df0a3cc)

Also, I tried to put it in .env, but no success.
It's strange because the same code and credential structure runs on the development environment and works greatly.

**Comment by waiting-for-dev** [comment] 2024-07-12 14:55
This is not something related to devise-jwt but to Rails credentials. I haven't been working with Rails for a while so I'm sorry not being able to help more here :/ I'll close the issue as this is not a bug, but anyone can feel free to post here and help you

**Closed by waiting-for-dev** 2024-07-12 14:55 UTC
Labels: bug
